config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'join', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 5000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :name, uniqueness: true
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase, self.username = username.downcase }
                                            #^ added based on self.email
  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # helper_method enables helpers to access controllers
  helper_method :current_user, :logged_in?

  def current_user
    # ||= if user not found at time of request, THEN...
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  def logged_in?
    # !! boolean or
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 10)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "Permission denied"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created successfully"
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Rename successful"
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 10)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "You do not have administrative privileges"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    # user = User.find_by(email: params[:session][:email].downcase)
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:alert] = "Incorrect credentials"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 10)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account has been updated successfully"
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog, #{@user.username}!"
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account deleted"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, :flash => { :error => "User not found" }
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "Permission denied"
        redirect_to @user
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 } )
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block" )
  end

end

app/helpers/pages_helper.rb
module PagesHelper
  
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="justify-content-md-center">
      <div class="col-8 mx-auto">
        <div class="card text-center shadow mt-3 mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            by <%= link_to article.user.username, user_path(article.user) %>
            <% if article.categories.any? %>
              <div class="mt-2">
                <%= render article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="btn btn-outline-success card-title"><%= link_to article.title, article_path(article), class: "text-dark text-decoration-none"%></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'View', article_path(article), class: "btn btn-success" %>

            <% if logged_in? && article.user == current_user %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-primary" %>
            <% end %>

            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'Delete', article_path(article), class: "btn btn-danger", data: { "turbo-method": :delete, "turbo_confirm": "Are you sure you wish to delete?" } %>
            <% end %>
          </div>

          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow", placeholder: "Title of article" %>
          </div>
        </div>

        <br>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow", placeholder: "Description of article" %>
          </div>
        </div>

        <br>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "PLACEHOLDER" }, { multiple: true, class: "form-select shadow" } ) %>
          </div>
        </div>

        <br>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-primary btn-lg shadow" %>
        </div>

        <br>

      <% end %>
    </div>
    
    <div class="text-center">
      <%= link_to 'Cancel', articles_path, class: "btn btn-danger shadow" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<% if logged_in? %>
  <h5 class="container col-2 mt-2 text-center btn btn-success"><%= link_to 'Create a new article', new_article_path, class: "text-white text-decoration-none" %></h5>
<% end %>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 mb-4">New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
    <div class="justify-content-md-center">
      <div class="col-8 mx-auto">
        <div class="card text-center shadow mt-3 mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            by <%= @article.user.username %>
            <%= link_to gravatar_for(@article.user, size: 24), user_path(@article.user) %>
            <% if @article.categories.any? %>
              <div class="mt-2">
                <%= render @article.categories %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-start"><%= simple_format(@article.description) %></div>
            <%= link_to 'Go Back', articles_path, class: "btn btn-success" %>
            <% if logged_in? && @article.user == current_user %>
              <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary" %>

            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to 'Delete', article_path(@article), class: "btn btn-danger", data: { "turbo-method": :delete, "turbo_confirm": "Are you sure you wish to delete?" } %>
            <% end %>

            <% end %>
          </div>
          
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div
        </div>
      </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info text-white text-decoration-none" %> 

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, local: true) do |f| %>

  <div class="container form-group col-6">
    <%= f.text_field :name, class: "form-control shadow", placeholder: "Enter category" %>
  </div>

  <br>

  <div class="container form-group col-6 text-center">
    <%= f.submit class: "btn btn-primary btn-lg shadow" %>
  </div>

  <br>

<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 mb-4">Rename Category</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">

      <%= render 'form' %>
      
    </div>
    
    <div class="text-center">
      <%= link_to 'Cancel', category_path, class: "btn btn-danger shadow" %>
    </div>

  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">Categories</h1>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="justify-content-md-center">
      <div class="col-6 mx-auto">
        <div class="card text-center shadow mt-3 mb-5 bg-white rounded">
          <div class="card-body">
            <h2 class="card-title"><%= link_to category.name, category_path(category), class: "text-dark text-decoration-none"%></h2>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>

          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(category.created_at) %> ago, edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 mb-4">New Category</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, local: true) do |f| %>

        <div class="container form-group col-6">
          <%= f.text_field :name, class: "form-control shadow", placeholder: "Enter category" %>
        </div>

        <br>

        <div class="container form-group col-6 text-center">
          <%= f.submit class: "btn btn-primary btn-lg shadow" %>
        </div>

        <br>

      <% end %>
    </div>
    
    <div class="text-center">
      <%= link_to 'Cancel', categories_path, class: "btn btn-danger shadow" %>
    </div>

  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 mb-2"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-2">
    <%= link_to 'Rename', edit_category_path(@category), class: "btn btn-primary" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <%= link_to 'Home', root_path, class: "nav-link px-2 text-muted" %>
      <%= link_to 'Articles', articles_path, class: "nav-link px-2 text-muted" %>
      <%= link_to 'Bloggers', users_path, class: "nav-link px-2 text-muted" %>
      
      <% if logged_in? %>
        <%= link_to 'Account', user_path(current_user), class: "nav-link px-2 text-muted" %>
      <% else %>
        <%= link_to 'Join', join_path, class: "nav-link px-2 text-muted" %>
      <% end %>

      <%= link_to 'About', about_path, class: "nav-link px-2 text-muted" %>
    </ul>
    <p class="text-center text-muted">© 2022 Denis Chernyavsky</p>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container col-4">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show mt-4" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if !logged_in? %>
          <%= link_to "Join", join_path, class: "nav-link text-light" %>
        <% end %>

        <%= link_to "Articles", articles_path, class: "nav-link text-light" %>

        <li class="navbar-nav mb-lg-0 dropdown">
          <% if logged_in? && current_user.admin %>
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories </a>
            <ul class="dropdown-menu">
              <%= link_to "View categories", categories_path, class: "dropdown-item" %>
              <li><hr class="dropdown-divider"></li>
              <%= link_to "New category", new_category_path, class: "dropdown-item" %>
            </ul>
          <% else %>
            <%= link_to "Categories", categories_path, class: "nav-link text-light" %>
          <% end %>
        </li>

        <%= link_to "Bloggers", users_path, class: "nav-link text-light" %>

        <%= link_to "About", about_path, class: "nav-link text-light" %>

      </ul>

      <li class="navbar-nav mb-2 me-1 mb-lg-0 nav-item dropdown">

        <% if logged_in? %>
          <%= link_to "Create", new_article_path, class: "nav-link text-light" %>
        <% end %>

        <a class="nav-link dropdown-toggle text-light" role="button" data-bs-toggle="dropdown" aria-expanded="false">Account </a>

        <% if logged_in? && current_user.admin %>
          <div class="nav-link">⭐</div>
        <% end %>

        <ul class="dropdown-menu text-light">
          <% if logged_in? %>
            <%= link_to "My profile", current_user, class: "dropdown-item" %>
            <%= link_to "Account settings", edit_user_path(current_user), class: "dropdown-item" %>
          <% else %>
            <%= link_to "Sign Up", join_path, class: "dropdown-item" %>
          <% end %>

          <li><hr class="dropdown-divider"></li>

          <% if logged_in? %>
            <%= link_to "Logout", logout_path, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Login", login_path, class: "dropdown-item" %>
          <% end %>
        </ul>
      </li>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column bg-color">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About AlphaBlog</h1>
<p>AlphaBlog is a project I'm working on for my Ruby On Rails bootcamp.</p>
<p>Homepage image provided by <a href="https://www.svgbackgrounds.com/" target="_blank">SVGBackgrounds.com</a></p>

<%= link_to 'Return home', root_path, method: :get %>

<a href="https://alpha-blog-702.herokuapp.com/" target="_blank">Heroku link</a>

app/views/pages/home.html.erb
<div class="container py-4">
  <div class="jumbotron p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5 text-center text-white">
      <h1 class="display-5 fw-bold text-shadow">Alpha Blog</h1>
      <p class="fs-4 text-shadow">Welcome to the home of the <b>ALPHA BLOG</b> project!</p>
      <%= link_to "Join", join_path, class: "btn btn-light btn-lg" %></button>
      <%= link_to "Articles", articles_path, class: "btn btn-light btn-lg" %></button>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> being saved!</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, local: true) do |f| %>

        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow", placeholder: "Enter a username" %>
          </div>
        </div>

        <br>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow", placeholder: "Enter your email" %>
          </div>
        </div>

        <br>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow", placeholder: "Enter a password" %>
          </div>
        </div>

        <br>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Join" : "Update", class: "btn btn-primary btn-lg shadow") %>
        </div>

        <br>

      <% end %>
    </div>
    
    <div class="text-center">
      <%= link_to 'Cancel', users_path, class: "btn btn-danger shadow" %>
    </div>

    
    <div class="mt-4 text-center">
      <% if logged_in? %>
        <%= link_to 'Delete my account', user_path(current_user), class: "text-decoration-none text-danger", method: :delete, data: { "turbo-method": :delete, "turbo_confirm": "Delete account?" }%>
      <% end %>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 mb-4">Account Settings</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-4">Bloggers</h1>

<div class="container">
  <% @users.each do |user| %>
    <div class="justify-content-md-center">
      <div class="col-8 mx-auto">
        <div class="card text-center shadow mt-3 mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <!--# Rails does not require 'user_path(user)', 'user' may be used -->
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to 'View profile', user, class: "btn btn-success" %>
            <% if logged_in? && user == current_user %>
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-primary" %>
            <% end %>

            <% if logged_in? && current_user.admin? %>
              <%= link_to 'Remove', user_path(user), class: "btn btn-danger", data: { "turbo-method": :delete, "turbo_confirm": "Are you sure you wish to remove this user?" } %>
            <% end %>

          </div>

          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4 mb-4">Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4 mb-4"><%= @user.username %></h1>

<div>
  <%= gravatar_for @user, size: 200 %>
</div>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to 'Edit Profile', edit_user_path, class: "btn btn-primary" %>
    <%= link_to 'Create Article', new_article_path, class: "btn btn-success" %>
  </div>
<% end %>

<h3 class="text-center mt-4 mb-2">Articles</h3>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="col-8 mx-auto apple_pagination mt-4 mb-4">
  <%= will_paginate @articles, :container => false %>
</div>